### ISSUE TITLE
Installing boost-histogram on Windows 10 PC

### ISSUE THREAD

**Issue by physicscitizen** [scikit-hep/boost-histogram#161]
It might be that you are not going to support or not supporting Windows 10 systems yet. But Henry S. was pretty insistant at PyHEP that we ought to be able to do:
>pip install boost-histogram
and get it to work!

I am on a Windows 10 mathine with 64-bit Python 3.8 successfully installed and also inside the PATH. numpy, awkward, and uproot have been successfully installed. Some of my simple test scripts work. 
Here is the sequence I get:<warning, it's long>
```
C:\Users\Todd Huffman>pip install boost-histogram
Collecting boost-histogram
  Downloading https://files.pythonhosted.org/packages/f9/82/bc8263134c445b98dc788c40fc3d7ae55831aca5708c4f7d1506b0b3b571/boost-histogram-0.5.1.tar.gz (421kB)
     |████████████████████████████████| 430kB 344kB/s
Requirement already satisfied: numpy in d:\python38\lib\site-packages (from boost-histogram) (1.17.2)
Installing collected packages: boost-histogram
  Running setup.py install for boost-histogram ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Todd Huffman\\AppData\\Local\\Temp\\pip-install-5unmjdm4\\boost-histogram\\setup.py'"'"'; __file__='"'"'C:\\Users\\Todd Huffman\\AppData\\Local\\Temp\\pip-install-5unmjdm4\\boost-histogram\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Todd Huffman\AppData\Local\Temp\pip-record-d7l6mm5r\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\
    Complete output (104 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\accumulators.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\algorithm.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\axis.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\numpy.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\storage.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\utils.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\version.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\_hist.py -> build\lib.win-amd64-3.8\boost_histogram
    copying boost_histogram\__init__.py -> build\lib.win-amd64-3.8\boost_histogram
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    building 'boost_histogram.core' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\Users
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram
    creating build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/module.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/module.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_algorithm.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_algorithm.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_axis.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_axis.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_histograms.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_histograms.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_storage.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_storage.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/assert/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/callable_traits/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/config/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/core/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/histogram/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/mp11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/pybind11/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/throw_exception/include -IC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\extern/variant2/include -Id:\python38\include -Id:\python38\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_accumulators.cpp /Fobuild\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_accumulators.obj /EHsc /bigobj /DVERSION_INFO=\"0.5.1\"
    C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:d:\python38\libs /LIBPATH:d:\python38\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019NEW\VC\Tools\MSVC\14.22.27905\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64 /EXPORT:PyInit_core build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/module.obj build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_algorithm.obj build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_axis.obj build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_histograms.obj build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_storage.obj build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src/register_accumulators.obj /OUT:build\lib.win-amd64-3.8\boost_histogram\core.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\src\core.cp38-win_amd64.lib
    running install_lib
    creating d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\accumulators.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\algorithm.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\axis.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\core.cp38-win_amd64.pyd -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\numpy.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\storage.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\utils.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\version.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\_hist.py -> d:\python38\Lib\site-packages\boost_histogram
    copying build\lib.win-amd64-3.8\boost_histogram\__init__.py -> d:\python38\Lib\site-packages\boost_histogram
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\accumulators.py to accumulators.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\algorithm.py to algorithm.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\axis.py to axis.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\numpy.py to numpy.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\storage.py to storage.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\utils.py to utils.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\version.py to version.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\_hist.py to _hist.cpython-38.pyc
    byte-compiling d:\python38\Lib\site-packages\boost_histogram\__init__.py to __init__.cpython-38.pyc
    running install_egg_info
    running egg_info
    writing boost_histogram.egg-info\PKG-INFO
    writing dependency_links to boost_histogram.egg-info\dependency_links.txt
    writing requirements to boost_histogram.egg-info\requires.txt
    writing top-level names to boost_histogram.egg-info\top_level.txt
    reading manifest file 'boost_histogram.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Todd Huffman\AppData\Local\Temp\pip-install-5unmjdm4\boost-histogram\setup.py", line 127, in <module>
        setup(
      File "d:\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "d:\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\python38\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "d:\python38\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "d:\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\python38\lib\site-packages\setuptools\command\install_egg_info.py", line 34, in run
        self.run_command('egg_info')
      File "d:\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\python38\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "d:\python38\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "d:\python38\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "d:\python38\lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
        self.read_manifest()
      File "d:\python38\lib\site-packages\setuptools\command\sdist.py", line 199, in read_manifest
        self.filelist.append(line)
      File "d:\python38\lib\site-packages\setuptools\command\egg_info.py", line 476, in append
        path = convert_path(item)
      File "d:\python38\lib\distutils\util.py", line 122, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/vsts/work/1/s/src/module.cpp' cannot be absolute
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Todd Huffman\\AppData\\Local\\Temp\\pip-install-5unmjdm4\\boost-histogram\\setup.py'"'"'; __file__='"'"'C:\\Users\\Todd Huffman\\AppData\\Local\\Temp\\pip-install-5unmjdm4\\boost-histogram\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Todd Huffman\AppData\Local\Temp\pip-record-d7l6mm5r\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Todd Huffman>
```
Any suggestions would be helpful!

**Comment by henryiii** [comment]
We do support Windows 10, but Windows + Python 3.8 does not have wheels yet. The build shouldn't die, though. Oddly, you seem to be getting a Windows Subsystem for Linux (WSL) path (starting with `/home`) instead of a Windows path. Are you sure things are not getting mixed up somehow? WSL paths shouldn't show up if you are building with MSVC...

Anyway, I think we can solve the issue by avoiding resolving paths in the boost-histogram setup.py. I'll make a patch, could you try installing from it when I do?

**Comment by henryiii** [comment]
Once builds pass, can you try doing:

```
python -m pip install git+https://github.com/scikit-hep/boost-histogram.git@henryiii-relpath
```

(or however you like calling pip)? Thanks for helping me debug Windows issues! I strongly support Windows when I can -- Hans does too in Boost.Histogram C++. We just don't like *using* it. :P

If you do have something mixed up and it's trying to install with Windows compilers in WSL, at least this should unearth the real issue.

I'm waiting on *Microsoft* Azure to start supporting Python 3.8 on Windows through wheels. Though in recent Python versions, even the compile should still *just work*:tm:.

**Comment by henryiii** [comment]
Should be ready to test.

**Comment by physicscitizen** [comment]
give me a bit of time. Turns out I did not install "git" on my PC so it doesn't understand what a "git clone" command is.

**Comment by henryiii** [comment]
I can get the SDist and attach it in a few minutes. CI produces it so I can copy it from there (but not on a phone).

**Comment by henryiii** [comment]
https://artifacts.dev.azure.com/scikit-hep/9bc38e61-98fd-4f7d-a4e7-be0eba487092/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3NjaWtpdC1oZXAvcHJvamVjdElkLzliYzM4ZTYxLTk4ZmQtNGY3ZC1hNGU3LWJlMGViYTQ4NzA5Mi9idWlsZElkLzEzMzIvYXJ0aWZhY3ROYW1lL0xpbnV4X0xpbnV4U0Rpc3Rfbm9uZQ2/content?format=zip&subPath=

Unzip that, then run pip on the tar.gz that’s inside.

**Comment by physicscitizen** [comment]
Looks like we have success!
```
C:\Users\Todd Huffman>pip install boost-histogram-0.5.1.tar.gz
Processing c:\users\todd huffman\boost-histogram-0.5.1.tar.gz
Requirement already satisfied: numpy in d:\python38\lib\site-packages (from boost-histogram==0.5.1) (1.17.2)
Installing collected packages: boost-histogram
  Running setup.py install for boost-histogram ... done
Successfully installed boost-histogram-0.5.1
WARNING: You are using pip version 19.2.3, however version 19.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Todd Huffman>
```
Since I have a day-job the next step (trying to actually USE this package to replicate a histogramming script that I currently have in ROOT but ported entirely to python) could take me a while. 
But this looks like a result so far!

**Comment by HDembinski** [comment]
I wish you good luck with the transition, Todd, and thanks to Henry for reacting so fast!

**Comment by henryiii** [comment]
Hi,
Hist does not exist yet; work on it will probably begin at the end of the year.

You can fairly easily display histograms, though, using something similar to what I showed at PyHEP; see https://github.com/henryiii/pres-bhandhist/blob/master/BoostHistogramHandsOn.ipynb .

```python
import matplotlib.pyplot as plt

def plothist(h):
    return plt.bar(h.axes[0].centers, h.view(), width=h.axes[0].widths);
```

I'll try to remember to ping you on this thread when hist is started!

**Comment by physicscitizen** [comment]
Hi Henry,
It took me a little while but I did finally get this to work. I’m new to matplotlib and so I did not appreciate at first that there was more to your code snippet below.

Basically I needed the following:


import matplotlib.pyplot as plt



def plothist(h):

    return plt.bar(h.axes[0].centers, h.view(), width=h.axes[0].widths);
#
# Then, after filling the histogram called ‘jhist’ …
#
ptHist = plothist(jhist)
plt.show()  # this was the crutial line.

I guess one thing that blows me away a bit is that you cannot do:
ptHist.show() and that, somehow, matplotlib just seems to “know” that this is your histogram.
I can understand this when I’ve only got one histogram to plot. But what happens if I have created and filled 10 of them, maybe some of them 2-d or 3d histograms?
Wouldn’t it be better if the thing (bar chart) you created using plt.bar() was the thing that you then operate on to “show” or to add labels and trappings (or decorations) to?

I accept I need to start reading up on the matplotlib documentation. But this does strike me as counter-intuitive and it might be good if ‘hist’ when started addressed some of this?

Cheers,
Todd

**Comment by henryiii** [comment]
Hi Todd,

My apologies, I *might* have remembered to include the `plt.show()` if I knew you were not familiar with Matplotlib, but then again, I might not have. When I'm in a Jupyter notebook (which is where I do almost any interactive exploration), there is no need for `plt.show()`; Jupyter will show the contents of the final item in the cell, including a plot. And when I'm in a script, I use savefig instead of show.

Matplotlib has two interfaces; one is "state-based", and mimics Matlab. It's fast and easy for interactive work, so I tend to use that one for quick plots. It is quite odd for Python users, though, who expect object-oriented interfaces. It also doesn't scale all that well (as you anticipated); you can do it, but it's ugly and very matlab-like.

If you'd like to use the object-oriented interface, the calls would look like this:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots() # Makes a figure and (by default) 1 axis
ax.bar(jhist.axes[0].centers, jhist.view(), width=jhist.axes[0].widths)
fig.show() # optional in a notebook
```

For plotting functions (Pandas is the go-to example for this), you accept an optional `ax=` keyword. If a user passes an axis, then it plots to that axis in OO fashion. If you do not, it creates a figure and axis automatically.

Matplotlib is a little clunky and verbose, but it has a tremendous amount of flexibility and supports a wide range of uses, such as interactive plots or high-quality PDF plots. There are *many* other libraries out there, written by people who didn't like some aspect of Matplotlib, but none of them have managed to cover all the uses Matplotlib has.

**Comment by henryiii** [comment]
You might find this useful. It has a section on Matplotlib. https://github.com/henryiii/compclass

**Comment by physicscitizen** [comment]
Thanks very much for all this!
I do appreciate it.

**Comment by physicscitizen** [comment]
I want to thank you again for the reference below. I’m finding it exceptionally helpful.

Cheers,
Todd
