### ISSUE TITLE
StrCategory `fill` Test

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#360]
https://github.com/scikit-hep/boost-histogram/blob/25efc58e1611bd4c2a713a0b593c4389eab09e78/tests/test_storage.py#L11-L22

@henryiii Have you ever test for the `fill` in histograms which composed by StrCategory? I didn't find tests related to `fill` method for StrCategory in test_axis.py and `fill` tests in test_storage.py only test for the Regular axis. I'm confused about why this code snippet doesn't work.

```python
import boost_histogram as bh

h = bh.Histogram(
    bh.axis.StrCategory(["F", "T"]),
    bh.axis.StrCategory(["F", "T"]),
    bh.axis.StrCategory(["F", "T"]),
).fill(
    ["T", "T", "T", "T", "T", "F", "T"],
    ["F", "T", "T", "F", "F", "T", "F"],
    ["F", "F", "T", "T", "T", "T", "T"],
)

z_one_only = h[{2: bh.loc("T")}]
assert z_one_only["F", "F"] == 0
assert z_one_only["F", "T"] == 1
assert z_one_only["T", "F"] == 3
assert z_one_only["T", "T"] == 1
``` 

Error (tested with BH==0.7.0):

```bash
$ python3 untitled.py 
Traceback (most recent call last):
  File "untitled.py", line 14, in <module>
    assert z_one_only["F", "F"] == 0
  File "/usr/local/lib/python3.7/site-packages/boost_histogram/_internal/hist.py", line 546, in __getitem__
    "Must be a slice, an integer, or follow the locator protocol."
IndexError: Must be a slice, an integer, or follow the locator protocol.
```

**Comment by henryiii** [comment]
The problem above is that you can't access directly with a string, you have to use a locator:

```python
assert z_one_only[bh.loc("F"), bh.loc("F")] == 0
assert z_one_only[bh.loc("F"), bh.loc("T")] == 1
assert z_one_only[bh.loc("T"), bh.loc("F")] == 3
assert z_one_only[bh.loc("T"), bh.loc("T")] == 1
```

This is how all histogram access works; it's more obvious why this works this way with an Integer or IntCategory histogram:

```python
h = bh.Histogram(bh.Integer(-5,6))
h[0] # Gets the first bin, the -5
h[bh.loc(0)] # Gets the middle bin, the 0
```

**Comment by henryiii** [comment]
Always happy to add tests, though. :)
