### ISSUE TITLE
[BUG] 1.5.0: Build fails

### ISSUE THREAD

**Issue by yurivict** [scikit-hep/boost-histogram#954]
**Describe the bug**
```
===>  Building for py311-boost-histogram-1.5.0
* Getting build dependencies for wheel...
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 380, in <module>
  |     main()
  |   File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 364, in main
  |     json_out["return_val"] = hook(**hook_input["kwargs"])
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 141, in get_requires_for_build_wheel
  |     return hook(config_settings)
  |            ^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/build/__init__.py", line 122, in get_requires_for_build_wheel
  |     requires = GetRequires.from_config_settings(config_settings)
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/builder/get_requires.py", line 64, in from_config_settings
  |     return cls(_load_scikit_build_settings(config_settings))
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/builder/get_requires.py", line 51, in _load_scikit_build_settings
  |     return SettingsReader.from_file("pyproject.toml", config_settings).settings
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/skbuild_read_settings.py", line 420, in from_file
  |     return cls(
  |            ^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/skbuild_read_settings.py", line 304, in __init__
  |     self.settings = self.sources.convert_target(ScikitBuildSettings)
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 586, in convert_target
  |     raise ExceptionGroup(msg, errors)
  | ExceptionGroup: Failed converting tool.scikit-build (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 540, in convert_target
    |     prep[field.name] = self.convert_target(
    |                        ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 586, in convert_target
    |     raise ExceptionGroup(msg, errors)
    | ExceptionGroup: Failed converting tool.scikit-build.cmake (1 sub-exception)
    | Field: tool.scikit-build.cmake
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 555, in convert_target
      |     tmp = source.convert(simple, field.type)
      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 493, in convert
      |     return raw_target(item)
      |            ^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/packaging/specifiers.py", line 718, in __init__
      |     self._specs = frozenset(map(Specifier, split_specifiers))
      |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/packaging/specifiers.py", line 237, in __init__
      |     raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      | packaging.specifiers.InvalidSpecifier: Invalid specifier: 'CMakeLists.txt'
      | Field tool.scikit-build.cmake.version
      +------------------------------------
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 555, in convert_target
    |     tmp = source.convert(simple, field.type)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/scikit_build_core/settings/sources.py", line 493, in convert
    |     return raw_target(item)
    |            ^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 202, in __init__
    |     raise InvalidVersion(f"Invalid version: '{version}'")
    | packaging.version.InvalidVersion: Invalid version: 'build-system.requires'
    | Field tool.scikit-build.minimum_version
    +------------------------------------

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
*** Error code 1
```

This patch fixes the build:
```
@@ -91,8 +91,6 @@ Homepage = "https://github.com/scikit-hep/boost-histog
 
 
 [tool.scikit-build]
-minimum-version = "build-system.requires"
-cmake.version = "CMakeLists.txt"
 metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
 sdist.exclude = [
   "extern/**/*.py",
```

Apparently these 2 lines contain bogus values.

Build is done using the 'build' module.

FreeBSD 14.1

**Comment by henryiii** [comment]
Scikit-build-core 0.10.0 is required. Though it’s required pretty much because of these two lines.

**Comment by yurivict** [comment]
Ok, thanks. I just commented out these lines for now.

**Comment by henryiii** [comment]
Sounds good. Once 0.10 is available inFreeBSD you can drop the patch. :)

**Comment by yurivict** [comment]
Thanks!
